// <auto-generated />
using ChargeHubAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargeHubAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChargeHubDbContext))]
    [Migration("20251125140734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChargeHubAPI.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CarCharge")
                        .HasColumnType("int");

                    b.Property<string>("Identecation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Identecation")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChargeHubAPI.Domain.Entities.User", b =>
                {
                    b.OwnsOne("ChargeHubAPI.Domain.Entities.Esp32Device", "Esp32", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("BtAddress")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Esp32BtAddress");

                            b1.Property<string>("BtName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Esp32BtName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ChargeHubAPI.Domain.Entities.StatusPosition", "StatusPosition", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(10)");

                            b1.Property<int>("East")
                                .HasColumnType("int")
                                .HasColumnName("StatusEast");

                            b1.Property<int>("North")
                                .HasColumnType("int")
                                .HasColumnName("StatusNorth");

                            b1.Property<int>("South")
                                .HasColumnType("int")
                                .HasColumnName("StatusSouth");

                            b1.Property<int>("West")
                                .HasColumnType("int")
                                .HasColumnName("StatusWest");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Esp32");

                    b.Navigation("StatusPosition");
                });
#pragma warning restore 612, 618
        }
    }
}
